language: android
jdk: oraclejdk8
sudo: required
before_script:
  - echo "global before_script"
script:
  # this script task will be ignored and jobs: will be run.
  - echo "global script" 
after_script:
  - echo "global after_script"
after_success:
  - echo "global after_success"
before_deploy:
  - echo "global before_deploy"
deploy:
  skip_cleanup: true
  provider: script
  script:
    # thid deploy script will be run after "test A" and "test B"
    - echo "global deploy"
after_deploy:
  - echo "global after_deploy"
jobs:
  include:
    - stage: test A
      script: 
        - echo "test script 1 A"
        - echo "test script 2 A"
    - stage: test B
      script: 
        - echo "test script 1 B"
        - echo "test script 2 B"
    - stage: deploy
      script: echo "test script in deploy"
      deploy:
        skip_cleanup: true
        provider: script
        script:
          # this script task will override "grobal deploy".
          - echo "deploy as a job"
