language: android
jdk: oraclejdk8
sudo: required
before_script:
  - echo "global before_script"
script:
  - echo "global script"
after_script:
  - echo "global after_script"
jobs:
  include:
    - stage: test
      script: echo "test script 1"
      script: echo "test script 2"
    - stage: deploy
      script: echo "test deploy"