language: android
jdk: oraclejdk8
sudo: required

stages:
  - test-a
  - name: deploy-1
    if: ( branch = master ) AND ( tag IS blank )
  - name: deploy-tag
    if: ( tag =~ ^beta.* ) OR ( tag =~ ^test.* )

before_script:
  - echo "global before_script"
script:
  # this script task will be ignored and jobs: will be run.
  - echo "global script" 
after_script:
  - echo "global after_script"
after_success:
  - echo "global after_success"
before_deploy:
  - echo "global before_deploy"
deploy:
  skip_cleanup: true
  provider: script
  script:
    # thid deploy script will be run after "test A" and "test B"
    - echo "global deploy"
after_deploy:
  - echo "global after_deploy"
jobs:
  include:
    - stage: test-a
      script: 
        - echo "test script 1 A"
        - echo "test script 2 A"
    - stage: test-b
      script: 
        - echo "test script 1 B"
        - echo "test script 2 B"
    - stage: deploy-1
      script: echo "test script in deploy 1"
      deploy:
        skip_cleanup: true
        provider: script
        script:
          # this script task will override "grobal deploy".
          - echo "deploy 1 as a job"
    - stage: deploy-tag
      script: echo "test script in deploy tag"
      deploy:
        skip_cleanup: true
        provider: script
        script:
          # this script task will override "grobal deploy".
          - echo "deploy tag as a job"

